Require swig 3.0.2
Build with swig 3.0.11 fails:

  import PyTrilinos.ML

  Traceback (most recent call last):
   File "/Users/guyer/anaconda/conda-bld/trilinos_1483368454886/test_tmp/run_test.py", line 33, in <module>
     import PyTrilinos.ML
   File "/Users/guyer/anaconda/conda-bld/trilinos_1483368454886/_t_env/lib/python2.7/site-packages/PyTrilinos/ML.py", line 142, in <module>
     import PyTrilinos.Teuchos
   File "/Users/guyer/anaconda/conda-bld/trilinos_1483368454886/_t_env/lib/python2.7/site-packages/PyTrilinos/Teuchos.py", line 4268, in <module>
     class DefaultComm:
   File "/Users/guyer/anaconda/conda-bld/trilinos_1483368454886/_t_env/lib/python2.7/site-packages/PyTrilinos/Teuchos.py", line 4270, in DefaultComm
     __defaultComm = MpiComm(mpiCommunicator)
   File "/Users/guyer/anaconda/conda-bld/trilinos_1483368454886/_t_env/lib/python2.7/site-packages/PyTrilinos/Teuchos.py", line 4184, in __init__
     raise AttributeError("No constructor defined")
  AttributeError: No constructor defined